import { fontFamily } from 'constants/constants';
import themeConstants from './constants';

export const buttonTheme = (theme = 'dark') => {
  return {
    primary: {
      backgroundColor: '#2E3142',
      borderRadius: '5px',
      color: '#FFFFFF',
      disabledBgColor: 'transparent',
      disabledBorder: '1px solid #3A3C46',
      disabledColor: '#3A3C46',
      fontFamily: 'Typold Medium',
      fontSize: '12px',
      height: '40px',
      lineHeight: '19px',
      onFocusBgColor: '#3A3C46',
      onFocusBorder: 'none',
      onFocusColor: '#67D6FF',
      onHoverBgColor: '#3A3C46',
      onHoverColor: '#67D6FF',
      padding: '14px 23px 16px',
      variant: 'contained',
    },
    secondary: {
      backgroundColor: 'transparent',
      border: '1px solid #2F3142',
      color: '#8C8C8C',
      disabledBgColor: 'transparent',
      disabledBorder: '1px solid #3A3C46',
      disabledColor: '#3A3C46',
      fontFamily: 'Typold Regular',
      fontSize: '12px',
      height: '40px',
      lineHeight: '19px',
      onFocusBgColor: '#3A3C46',
      onFocusBorder: '1px solid #3A3C46',
      onFocusColor: '#FFFFFF',
      onHoverBgColor: '#3A3C46',
      onHoverBorder: '1px solid #3A3C46',
      onHoverColor: '#FFFFFF',
      padding: '10px 20px 11px',
      variant: 'contained',
    },
    other: {
      backgroundColor: themeConstants[theme].colorButtonNormalGrey,
      border: 'none',
      color: themeConstants[theme].colorLightGrey,
      disabledColor: '#3A3C46',
      disabledBgColor: 'transparent',
      disabledBorder: '1px solid #3A3C46',
      fontFamily: fontFamily.regular,
      fontSize: '14px',
      height: '40px',
      lineHeight: '19px',
      onFocusBgColor: themeConstants[theme].colorGradientHighlights,
      onFocusBorder: 'none',
      onFocusColor: themeConstants[theme].colorWhite,
      onHoverBgColor: themeConstants[theme].colorButtonHoverGrey,
      onHoverBorder: 'none',
      onHoverColor: themeConstants[theme].colorWhite,
      padding: '10px 20px 11px',
      variant: 'contained',
    },
    switch: {
      inActiveBgColor: themeConstants[theme].colorDarkGrey,
      activeColor: themeConstants[theme].colorButtonSwitchActive,
      activeBgColor: themeConstants[theme].colorDarkGrey,
      activeHoverColor: themeConstants[theme].colorButtonSwitchActive,
      activeHoverBgColor: themeConstants[theme].colorDarkGrey,
      inActiveColor: themeConstants[theme].colorButtonSwitchInActive,
      inActiveHoverBgColor: themeConstants[theme].colorDarkGrey,
      inActiveHoverColor: themeConstants[theme].colorButtonSwitchInActive,
      height: '30px',
      minWidth: '50px',
    },
    toggle: {
      activeBtnBgColor: themeConstants[theme].colorEnglishGrey,
      activeBtnColor: themeConstants[theme].colorWhite,
      borderRadius: '5px',
      btnGroupBgColor: themeConstants[theme].colorDarkGrey,
      btnGroupSpacing: '4px',
      height: '40px',
      inActiveBtnBgColor: themeConstants[theme].colorDarkGrey,
      inActiveBtnColor: themeConstants[theme].colorLightGrey,
      labelColor: themeConstants[theme].colorLightGrey,
      width: '270px',
      labelSize: '12px',
      disabledColor: '#3A3C46',
      disabledBgColor: '#1B1C24',
      disabledBorder: '1px solid #3A3C46',
    },
    info: {
      backgroundColor: 'transparent',
      border: 'none',
      color: themeConstants[theme].colorButtonHoverGrey,
      disabledColor: '#3A3C46',
      disabledBgColor: 'transparent',
      disabledBorder: '1px solid #3A3C46',
      fontFamily: fontFamily.regular,
      fontSize: '14px',
      height: '20px',
      width: '20px',
      minWidth: '20px',
      lineHeight: '19px',
      onFocusBgColor: 'transparent',
      onFocusBorder: 'none',
      onFocusColor: themeConstants[theme].colorWhite,
      onHoverBgColor: 'transparent',
      onHoverBorder: 'none',
      onHoverColor: themeConstants[theme].colorButtonHoverGrey,
      padding: '0',
      variant: 'contained',
    },
    white: {
      backgroundColor: themeConstants[theme].colorWhite,
      borderRadius: '5px',
      height: '30px',
      width: '68px',
      minWidth: '68px',
      color: themeConstants[theme].colorBGGrey,
      disabledColor: '#3A3C46',
      disabledBgColor: 'transparent',
      disabledBorder: '1px solid #3A3C46',
      fontFamily: fontFamily.book,
      fontSize: '12px',
      lineHeight: '14px',
      onFocusBgColor: themeConstants[theme].colorWhite,
      onFocusBorder: 'none',
      onFocusColor: themeConstants[theme].colorBGGrey,
      onHoverBgColor: themeConstants[theme].colorWhite,
      onHoverBorder: 'none',
      onHoverColor: themeConstants[theme].colorBGGrey,
      padding: '0',
      variant: 'contained',
    },
    settings: {
      backgroundColor: themeConstants[theme].colorDarkGrey,
      border: 'none',
      color: themeConstants[theme].colorLightGrey,
      borderRadius: '50%',
      fontSize: '12px',
      width: '44px',
      height: '44px',
      minWidth: '44px',
      lineHeight: '19px',
      padding: '0',
      onHoverBgColor: themeConstants[theme].colorDarkGrey,
      onHoverBorder: '',
      onHoverColor: themeConstants[theme].colorWhite,
    },
    status: {
      backgroundColor: themeConstants[theme].colorDarkGrey,
      borderRadius: '5px',
      height: '30px',
      color: themeConstants[theme].colorSkyBlur,
      fontFamily: fontFamily.bold,
      fontSize: '12px',
      lineHeight: '16px',
      onFocusBgColor: themeConstants[theme].colorDarkGrey,
      onFocusBorder: 'none',
      onFocusColor: themeConstants[theme].colorSkyBlur,
      onHoverBgColor: themeConstants[theme].colorDarkGrey,
      onHoverBorder: 'none',
      onHoverColor: themeConstants[theme].colorSkyBlur,
      padding: '7px 15px',
      variant: 'contained',
    },
    close: {
      backgroundColor: themeConstants[theme].colorDarkBlue,
      border: 'none',
      borderRadius: '5px',
      color: themeConstants[theme].colorWhite,
      disabledColor: '#3A3C46',
      disabledBgColor: 'transparent',
      disabledBorder: '1px solid #3A3C46',
      fontFamily: fontFamily.bold,
      fontSize: '14px',
      height: '62px',
      lineHeight: '19px',
      onFocusBgColor: themeConstants[theme].colorDarkBlue,
      onFocusBorder: 'none',
      onFocusColor: '',
      onHoverBgColor: themeConstants[theme].colorDarkBlue,
      onHoverBorder: 'none',
      onHoverColor: '',
      padding: '14px 23px 16px',
      variant: 'contained',
    },
    active: {
      backgroundColor: themeConstants[theme].colorButtonNormalGrey,
      border: 'none',
      borderRadius: '5px',
      color: themeConstants[theme].colorPeacockBlue,
      disabledColor: '#3A3C46',
      disabledBgColor: 'transparent',
      disabledBorder: '1px solid #3A3C46',
      fontFamily: fontFamily.bold,
      fontSize: '12px',
      height: '38px',
      lineHeight: '16px',
      onFocusBgColor: themeConstants[theme].colorButtonNormalGrey,
      onFocusBorder: 'none',
      onFocusColor: '',
      onHoverBgColor: themeConstants[theme].colorButtonNormalGrey,
      onHoverBorder: 'none',
      onHoverColor: '',
      padding: '14px 23px 16px',
      variant: 'contained',
    },
    inActive: {
      backgroundColor: themeConstants[theme].colorCardGrey,
      border: 'none',
      borderRadius: '5px',
      color: themeConstants[theme].colorLightGrey,
      disabledColor: '#3A3C46',
      disabledBgColor: 'transparent',
      disabledBorder: '1px solid #3A3C46',
      fontFamily: fontFamily.regular,
      fontSize: '12px',
      height: '38px',
      lineHeight: '16px',
      onFocusBgColor: themeConstants[theme].colorCardGrey,
      onFocusBorder: 'none',
      onFocusColor: '',
      onHoverBgColor: themeConstants[theme].colorCardGrey,
      onHoverBorder: 'none',
      onHoverColor: '',
      padding: '11px 15px',
      variant: 'contained',
    },
    command: {
      backgroundColor: themeConstants[theme].colorUIElementGrey,
      border: 'none',
      borderRadius: '5px',
      color: themeConstants[theme].colorLightGrey,
      disabledColor: '#3A3C46',
      disabledBgColor: 'transparent',
      disabledBorder: '1px solid #3A3C46',
      fontFamily: fontFamily.regular,
      fontSize: '12px',
      width: '170px',
      height: '70px',
      lineHeight: '16px',
      onFocusBgColor: themeConstants[theme].colorUIElementGrey,
      onFocusBorder: 'none',
      onFocusColor: themeConstants[theme].colorWhite,
      onHoverBgColor: themeConstants[theme].colorUIElementGrey,
      onHoverBorder: 'none',
      onHoverColor: themeConstants[theme].colorWhite,
      padding: '11px 15px',
      variant: 'contained',
    },
  };
};
