import themeConstants from './constants';

const dropdownTheme = (theme = 'dark') => {
  return {
    primary: {
      dropdownBackground: themeConstants[theme].colorEnglishGrey,
      iconColor: themeConstants[theme].colorWhite,
      labelColor: themeConstants[theme].colorLightGrey,
      menuColor: themeConstants[theme].colorWhite,
      menuHoverBackground: themeConstants[theme].colorEnglishGrey,
      popupBackground: themeConstants[theme].colorCardGrey,
      popupBorderColor: themeConstants[theme].colorDarkBlackBlue,
      selectedMenuColor: themeConstants[theme].colorWhite,
      selectedValueColor: themeConstants[theme].colorPeacockBlue,
      width: '270px',
      height: '40px',
      disabledColor: '#3A3C46',
      disabledBgColor: 'transparent',
      disabledBorder: '1px solid #3A3C46',
    },
    secondary: {
      dropdownBackground: themeConstants[theme].colorEnglishGrey,
      iconColor: themeConstants[theme].colorWhite,
      labelColor: themeConstants[theme].colorLightGrey,
      menuColor: themeConstants[theme].colorWhite,
      menuHoverBackground: themeConstants[theme].colorEnglishGrey,
      popupBackground: themeConstants[theme].colorCardGrey,
      popupBorderColor: themeConstants[theme].colorDarkBlackBlue,
      selectedMenuColor: themeConstants[theme].colorWhite,
      width: '270px',
      height: '40px',
      disabledColor: '#3A3C46',
      disabledBgColor: 'transparent',
      disabledBorder: '1px solid #3A3C46',
    },
    sorting: {
      height: '40px',
      backgroundColor: '#2F3142',
      dropdownBackground: '#1B1C24',
      iconColor: '#FFFFFF',
      labelColor: '#8C8C8C',
      menuColor: '#8C8C8C',
      menuHoverBackground: '#2F3142',
      onActiveBackground: '#2F3141',
      onActiveColor: '#67D6FF',
      popupBackground: '#1B1C24',
      popupBorderColor: '#2E3036',
      width: 'auto',
      selectedMenuColor: '#FFFFFF',
      selectedValueColor: themeConstants[theme].colorPeacockBlue,
      searchStyle: {
        backgroundColor: '#14151E',
      },
      typographyStyle: {
        color: '#FFFFFF',
        font: 'Typold Bold',
        letterSpacing: '2.57px',
        lineHeight: '16px',
        margin: '20px 20px 15px',
        size: '12px',
      },
      inputStyle: {
        borderRadius: '5px',
        color: '#FFFFFF',
        disabledBgColor: 'transparent',
        disabledBorder: '1px solid #2E3037',
        disabledColor: '#3A3C46',
        fontFamily: 'Typold Regular',
        fontSize: '12px',
        height: '40px',
        iconColor: '#fff',
        iconFontSize: '14px',
        inputBorder: '1px solid transparent',
        onHoverBgColor: '#3A3C46',
        onHoverBorder: '1px solid #fff',
        onHoverColor: '#FFFFFF',
        padding: '5px',
        width: '326px',
      },
      RadioStyle: {
        backgroundChecked: '#83D4FF',
        backgroundColor: '#14151E',
        backgroundDisabled: '#2E3142',
        border: '1px solid #8C8C8C',
        borderChecked: '1px solid #83D4FF',
        borderDisabled: '1px solid #3A3C46',
      },
      buttonStyle: {
        backgroundColor: '#2E3142',
        border: 'none',
        color: '#FFF',
        disabledBgColor: '#666',
        disabledBorder: '1px solid #ccc',
        disabledColor: '#ccc',
        fontFamily: 'Typold Regular',
        fontSize: '12px',
        height: '40px',
        lineHeight: '14px',
        onFocusBgColor: 'linear-gradient(135deg, #75CFFF 0%, #5735FD 100%)',
        onFocusBorder: 'none',
        onFocusColor: '#FFFFFF',
        onHoverBgColor: '#3A3C45',
        onHoverBorder: 'none',
        onHoverColor: '#FFFFFF',
        padding: '10px 20px 11px',
        variant: 'contained',
        width: 'auto',
      },
      dividerStyle: {
        backgroundColor: '#101012',
        height: '1px',
        margin: '15px 0px',
        onHoverBackground: '#101012',
        opacity: '100%',
        width: 'auto',
      },
    },
    group: {
      selectedMenuColor: '#FFFFFF',
      width: 'auto',
      backgroundColor: '#2F3142',
      dropdownBackground: '#1B1C24',
      height: '40px',
      iconColor: '#FFFFFF',
      menuColor: '#8C8C8C',
      menuHoverBackground: '#2F3142',
      onActiveBackground: '#2F3141',
      onActiveColor: '#67D6FF',
      popupBackground: '#1B1C24',
      popupBorderColor: '#2E3036',
      disabledColor: '#3A3C46',
      disabledBgColor: 'transparent',
      disabledBorder: '1px solid #3A3C46',
      RadioStyle: {
        backgroundChecked: '#83D4FF',
        backgroundColor: '#14151E',
        backgroundDisabled: '#2E3142',
        border: '1px solid #8C8C8C',
        borderChecked: '1px solid #83D4FF',
        borderDisabled: '1px solid #3A3C46',
      },
      buttonStyle: {
        backgroundColor: '#2E3142',
        border: 'none',
        color: '#FFF',
        disabledBgColor: '#666',
        disabledBorder: '1px solid #ccc',
        disabledColor: '#ccc',
        fontFamily: 'Typold Regular',
        fontSize: '12px',
        height: '40px',
        lineHeight: '14px',
        onFocusBgColor: 'linear-gradient(135deg, #75CFFF 0%, #5735FD 100%)',
        onFocusBorder: 'none',
        onFocusColor: '#FFFFFF',
        onHoverBgColor: '#3A3C45',
        onHoverBorder: 'none',
        onHoverColor: '#FFFFFF',
        padding: '10px 20px 11px',
        variant: 'contained',
        width: 'auto',
      },
      dividerStyle: {
        backgroundColor: '#101012',
        height: '1px',
        margin: '15px 0px',
        onHoverBackground: '#101012',
        opacity: '100%',
        width: 'auto',
      },
      inputStyle: {
        borderRadius: '5px',
        color: '#FFFFFF',
        disabledBgColor: 'transparent',
        disabledBorder: '1px solid #2E3037',
        disabledColor: '#3A3C46',
        fontFamily: 'Typold Regular',
        fontSize: '12px',
        height: '40px',
        iconColor: '#fff',
        iconFontSize: '14px',
        inputBorder: '1px solid transparent',
        onHoverBgColor: '#3A3C46',
        onHoverBorder: '1px solid #fff',
        onHoverColor: '#FFFFFF',
        padding: '5px',
        width: '326px',
      },
      searchStyle: {
        backgroundColor: '#14151E',
      },
      typographyStyle: {
        color: '#FFFFFF',
        font: 'Typold Bold',
        letterSpacing: '2.57px',
        lineHeight: '16px',
        margin: '20px 20px 15px',
        size: '12px',
      },
    },
    autoComplete: {
      iconsColor: '#FFFFFF',
      inputBackground: '#2F3141',
      inputColor: '#8C8C8C',
      inputOnFocusColor: '#FFFFFF',
      inputOnHoverBackground: '#2F3141',
      inputOnHoverColor: '#FFFFFF',
      labelColor: '#8C8C8C',
      listItemColor: '#FFFFFF',
      listItemOnSelectBackground: '#2F3142',
      paperBackground: '#2F3141',
      disabledColor: '#3A3C46',
      disabledBgColor: 'transparent',
      disabledBorder: '1px solid #3A3C46',
    },
    commands: {
      dropdownBackground: themeConstants[theme].colorEnglishGrey,
      iconColor: themeConstants[theme].colorWhite,
      labelColor: themeConstants[theme].colorLightGrey,
      menuColor: themeConstants[theme].colorWhite,
      menuHoverBackground: themeConstants[theme].colorEnglishGrey,
      popupBackground: themeConstants[theme].colorCardGrey,
      popupBorderColor: themeConstants[theme].colorDarkBlackBlue,
      selectedMenuColor: themeConstants[theme].colorWhite,
      width: '270px',
      height: '40px',
      disabledColor: '#3A3C46',
      disabledBgColor: 'transparent',
      disabledBorder: '1px solid #2E3037',
    },
  };
};

export default dropdownTheme;
