import themeConstants from './constants';

export const inputTheme = (theme = 'dark') => {
  return {
    primary: {
      backgroundColor: themeConstants[theme].colorEnglishGrey,
      borderRadius: '5px',
      color: themeConstants[theme].colorWhite,
      fontSize: '12px',
      inputBorder: '1px solid transparent',
      labelColor: themeConstants[theme].colorLightGrey,
      lineHeight: '16px',
      padding: '12px 10px',
      width: '270px',
      labelSize: '12px',
      onHoverBgColor: themeConstants[theme].colorBlueGrey,
      onHoverBorder: `1px solid ${themeConstants[theme].colorWhite}`,
      onHoverColor: themeConstants[theme].colorWhite,
      disabledBgColor: 'transparent',
      disabledBorder: `1px solid ${themeConstants[theme].colorNormalBlueGrey}`,
      disabledColor: themeConstants[theme].colorBlueGrey,
    },
    searchBox: {
      backgroundColor: themeConstants[theme].colorUIElementGrey,
      borderRadius: '5px',
      color: themeConstants[theme].colorWhite,
      fontFamily: 'Typold Regular',
      fontSize: '12px',
      height: '40px',
      iconFontSize: '14px',
      inputBorder: '1px solid transparent',
      onHoverBgColor: themeConstants[theme].colorBlueGrey,
      onHoverBorder: `1px solid ${themeConstants[theme].colorWhite}`,
      onHoverColor: themeConstants[theme].colorWhite,
      width: '574px',
      disabledBgColor: 'transparent',
      disabledBorder: `1px solid ${themeConstants[theme].colorNormalBlueGrey}`,
      disabledColor: themeConstants[theme].colorBlueGrey,
      iconColor: '#FFF',
    },
    searchBoxSecondary: {
      backgroundColor: themeConstants[theme].colorDarkGrey,
      borderRadius: '5px',
      color: themeConstants[theme].colorWhite,
      fontFamily: 'Typold Regular',
      fontSize: '12px',
      height: '40px',
      iconFontSize: '14px',
      inputBorder: 'none',
      onHoverBgColor: themeConstants[theme].colorBlueGrey,
      onHoverBorder: (props) => props.onHoverBorder,
      onHoverColor: themeConstants[theme].colorWhite,
      width: '574px',
      disabledBgColor: 'transparent',
      disabledBorder: `1px solid ${themeConstants[theme].colorNormalBlueGrey}`,
      disabledColor: themeConstants[theme].colorBlueGrey,
      iconColor: '#FFF',
    },
    uploaderInput: {
      backgroundColor: themeConstants[theme].colorDarkGrey,
      borderRadius: '5px',
      color: themeConstants[theme].colorWhite,
      fontSize: '12px',
      inputBorder: 'none',
      labelColor: themeConstants[theme].colorLightGrey,
      lineHeight: '16px',
      padding: '12px 10px',
    },
    maskedInput: {
      inputBackgroundColor: themeConstants[theme].colorEnglishGrey,
      inputColor: themeConstants[theme].colorWhite,
      inputWidth: '570px',
      labelColor: themeConstants[theme].colorLightGrey,
    },
  };
};
