// Device Action Types
export const STORE_DEVICE_DATA = 'STORE_DEVICE_DATA';
export const DEVICE_ERROR = 'DEVICE_ERROR';
export const SET_SELECTED_DEVICE_INDEX = 'SET_SELECTED_DEVICE_INDEX';

// Theme Action Types
export const TOGGLE_THEME = 'TOGGLE_THEME';
// Animation render flag types
export const SET_COMPONENT_RENDER = 'SET_COMPONENT_RENDER';

// User Action Types
export const STORE_USER_DATA = 'STORE_USER_DATA';
export const USER_ERROR = 'USER_ERROR';

// Device details types
export const STORE_DEVICE_DETAILS_DATA = 'STORE_DEVICE_DETAILS_DATA';
export const DEVICE_DETAILS_ERROR = 'DEVICE_DETAILS_ERROR';
export const DEVICE_DETAILS_CHANGED = 'DEVICE_DETAILS_CHANGED';
export const SAVE_DEVICE_DETAILS_CHANGES = 'SAVE_DEVICE_DETAILS_CHANGES';
export const CANCEL_DEVICE_DETAILS_CHANGES = 'CANCEL_DEVICE_DETAILS_CHANGES';
export const TOGGLE_DEVICE_CHANGES_CONFIRMATION_DIALOG =
  'TOGGLE_DEVICE_CHANGES_CONFIRMATION_DIALOG';
export const DEVICE_TAB_VALUE = 'DEVICE_TAB_VALUE';
export const DEVICE_TAB_VALUE_TO_BE = 'DEVICE_TAB_VALUE_TO_BE';
export const INITIALIZE_DEVICE_DETAILS = 'INITIALIZE_DEVICE_DETAILS';
export const SET_DEVICE_DETAILS_LOADER = 'SET_DEVICE_DETAILS_LOADER';

// Device group types
export const STORE_DEVICE_GROUP_DATA = 'STORE_DEVICE_GROUP_DATA';
export const DEVICE_GROUP_ERROR = 'DEVICE_GROUP_ERROR';
export const SET_SELECTED_DEVICES = 'SET_SELECTED_DEVICES';
export const STORE_DEVICE_GROUP_DEVICES = 'STORE_DEVICE_GROUP_DEVICES';

// Global Error, success handling and loader
export const GLOBAL_SHOW_ALERT = 'GLOBAL_SHOW_ALERT';
export const GLOBAL_HIDE_ALERT = 'GLOBAL_HIDE_ALERT';
export const GLOBAL_SHOW_LOADER = 'GLOBAL_SHOW_LOADER';
export const GLOBAL_HIDE_LOADER = 'GLOBAL_HIDE_LOADER';

// GLOBAL filter show hide
export const GLOBAL_FILTER_SHOW = 'GLOBAL_FILTER_SHOW';
export const GLOBAL_FILTER_HIDE = 'GLOBAL_FILTER_HIDE';

// Global Client List
export const SET_GLOBAL_CLIENT_LIST = 'SET_GLOBAL_CLIENT_LIST';
