import React from 'react';
import Uploader from '.';

export default {
  title: 'Components/Uploader',
  component: Uploader,
  argTypes: {
    onClick: { action: 'clicked' },
  },
};

const Template = (args) => {
  const {
    onDragColor,
    width,
    minWidth,
    maxWidth,
    height,
    minHeight,
    maxHeight,
    background,
    fontFamily,
    fontSize,
    lineHeight,
    letterSpacing,
    textAlign,
    color,
    padding,
    borderWidth,
    borderRadius,
    borderColor,
    activeBorderColor,
    acceptedBorderColor,
    acceptedBackgroundColor,
    rejectedBackgroundColor,
    buttonPrimaryBackgroundColor,
    buttonPrimaryBorder,
    buttonPrimaryBorderRadius,
    buttonPrimaryColor,
    buttonPrimaryDisabledBgColor,
    buttonPrimaryDisabledBorder,
    buttonPrimaryDisabledColor,
    buttonPrimaryFontFamily,
    buttonPrimaryFontSize,
    buttonPrimaryHeight,
    buttonPrimaryLineHeight,
    buttonPrimaryOnFocusBgColor,
    buttonPrimaryOnFocusBorder,
    buttonPrimaryOnFocusColor,
    buttonPrimaryOnHoverBgColor,
    buttonPrimaryOnHoverBorder,
    buttonPrimaryOnHoverColor,
    buttonPrimaryPadding,
    buttonPrimaryVariant,
    imagePreviewStyle,
    src,
  } = args;

  return (
    <Uploader
      src={src}
      imagePreviewStyle={imagePreviewStyle}
      styles={{
        onDragColor,
        width,
        minWidth,
        maxWidth,
        height,
        minHeight,
        maxHeight,
        background,
        fontFamily,
        fontSize,
        lineHeight,
        letterSpacing,
        textAlign,
        color,
        padding,
        borderWidth,
        borderRadius,
        borderColor,
        activeBorderColor,
        acceptedBorderColor,
        acceptedBackgroundColor,
        rejectedBackgroundColor,
      }}
      buttonPrimaryTheme={{
        backgroundColor: buttonPrimaryBackgroundColor,
        border: buttonPrimaryBorder,
        borderRadius: buttonPrimaryBorderRadius,
        color: buttonPrimaryColor,
        disabledBgColor: buttonPrimaryDisabledBgColor,
        disabledBorder: buttonPrimaryDisabledBorder,
        disabledColor: buttonPrimaryDisabledColor,
        fontFamily: buttonPrimaryFontFamily,
        fontSize: buttonPrimaryFontSize,
        height: buttonPrimaryHeight,
        lineHeight: buttonPrimaryLineHeight,
        onFocusBgColor: buttonPrimaryOnFocusBgColor,
        onFocusBorder: buttonPrimaryOnFocusBorder,
        onFocusColor: buttonPrimaryOnFocusColor,
        onHoverBgColor: buttonPrimaryOnHoverBgColor,
        onHoverBorder: buttonPrimaryOnHoverBorder,
        onHoverColor: buttonPrimaryOnHoverColor,
        padding: buttonPrimaryPadding,
        variant: buttonPrimaryVariant,
      }}
    />
  );
};

export const Default = Template.bind({});

Default.args = {
  onDragColor: '#FFFF',
  width: '690px',
  minWidth: '690px',
  maxWidth: '690px',
  height: '350px ',
  minHeight: '350px',
  maxHeight: '350px',
  background: '#09090A',
  fontFamily: 'Typold Regular',
  fontSize: '12px',
  lineHeight: '16px',
  letterSpacing: 'normal',
  textAlign: 'center',
  color: '#8C8C8C',
  padding: '20px',
  borderWidth: 20,
  borderRadius: 2,
  borderColor: '#09090A',
  activeBorderColor: '#2196f3',
  acceptedBorderColor: '#12A9DA',
  acceptedBackgroundColor: '#3A3C45',
  rejectedBackgroundColor: '#ff1744',
  buttonPrimaryBackgroundColor: 'transparent',
  buttonPrimaryBorder: '1px solid #83D4FF',
  buttonPrimaryBorderRadius: '5px',
  buttonPrimaryColor: '#83D4FF',
  buttonPrimaryDisabledBgColor: '#666',
  buttonPrimaryDisabledBorder: '2px solid #ccc',
  buttonPrimaryDisabledColor: '#ccc',
  buttonPrimaryFontFamily: 'Typold Medium',
  buttonPrimaryFontSize: '14px',
  buttonPrimaryHeight: '40px',
  buttonPrimaryLineHeight: '19px',
  buttonPrimaryOnFocusBgColor: 'linear-gradient(135deg, #75CFFF 0%, #5735FD 100%)',
  buttonPrimaryOnFocusBorder: '1px solid transparent',
  buttonPrimaryOnFocusColor: '#FFFFFF',
  buttonPrimaryOnHoverBgColor: 'transparent',
  buttonPrimaryOnHoverBorder: '1px solid #83D4FF',
  buttonPrimaryOnHoverColor: '#83D4FF',
  buttonPrimaryPadding: '10px 17px 10px 10px',
  buttonPrimaryVariant: 'contained',
  imagePreviewStyle: {
    styles: { width: '250px', height: '250px', background: '#09090A' },
    buttonStyles: { color: '#FFF', background: '#2E3142', fontFamily: 'Typold Medium' },
    avatarStyles: { width: '140px', height: '140px' },
    iconStyles: { color: '#8C8C8C' },
  },
  src: '',
};
