export const deviceDetailsStore = {
  device: {
    id: null,
    deviceId: '',
    deviceName: '',
    deviceStatus: '',
    lastBeatReceivedOn: null,
    orientationType: '',
    platform: '',
    platformAppName: null,
    platformAppVersion: null,
    lanMacAddress: null,
    lanIpAddress: null,
    wiFiMacAddress: null,
    wiFiIpAddress: null,
    fdqnAddress: null,
    ram: '',
    ramFree: '',
    ramUsed: '',
    storage: '',
    storageFree: '',
    storageUsed: '',
    viewerSessionId: null,
    teamViewerId: '',
    installationLocation: null,
    displayNames: null,
    firmware: null,
  },
  message: '',
  isError: false,
  isChanged: false,
  isSaveChanges: false,
  isCancelChanges: false,
  showConfirmationDialog: false,
  tabValue: 0,
  loader: false,
  tabValueToBeSet: null,
};

export default deviceDetailsStore;
