const projectCreationTheme = {
  dark: {
    drawer: {
      background: '#1F1F35',
      height: '40%',
      color: '#fff',
      border: '3px solid #3AB6FF',
      backdropFilter: 'blur(10px)',
      top: 'auto',
      padding: '0',
    },
    typographyPrimary: {
      color: '#8C8C8C',
      font: 'Typlod Regular',
      lineHeight: '25px',
      margin: '0 0 17px 0',
      size: 'xl',
      textAlign: 'left',
    },
    typographySecondary: {
      color: 'secondary',
      font: 'medium',
      lineHeight: '16px',
      margin: '0 0 5px 0',
      size: 'sm',
      textAlign: 'left',
    },
    buttonPrimary: {
      disabledBgColor: '#666',
      disabledBorder: '1px solid #ccc',
      disabledColor: '#ccc',
      fontFamily: 'Typold Regular',
      fontSize: '14px',
      height: '40px',
      lineHeight: '19px',
      onHoverBorder: '1px solid #3AB6FF',
      padding: '10px 20px 11px',
      variant: 'contained',
    },
    buttonSwitch: {
      activeBtnBgColor: '#3AB6FF',
      activeBtnColor: '#FFFFFF',
      borderRadius: '0',
      btnGroupBgColor: '#404153',
      btnGroupSpacing: '4px',
      height: '40px',
      inActiveBtnBgColor: '#404153',
      inActiveBtnColor: '#FFFFFF',
      labelColor: '#7E80A7',
      width: '270px',
    },
  },
};

export default projectCreationTheme;
